apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        appVersion: v1.2
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:mainline-alpine
          ports:
            - containerPort: 80
              protocol: TCP
